# Generated by Django 5.0.1 on 2024-07-11 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0002_alter_stores_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stores',
            old_name='Rating',
            new_name='rating',
        ),
    ]
