# Generated by Django 5.0.1 on 2024-07-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0005_items_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
