# Generated by Django 5.0.1 on 2024-07-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0006_alter_items_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='image',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
